baseURL: https://danaukes.com/
languageCode: en-us
title: Foldable Robotics

enableInlineShortcodes: true

params: 
  menu:
    - name: Canvas
      link: https://canvas.asu.edu/
      external: true
  author: Daniel M. Aukes
  home: ""
  description: Making better Foldable Robots

ignorefiles:
  - "content/modules/biomechanics/_drafts"
  - "content/modules/introduction/_drafts"
  - "content/modules/integration/_drafts"
  - "content/modules/dynamics/_drafts"
  - "content/modules/compliance/_drafts"
  - "assignments/_drafts"  