baseURL: https://danaukes.com/
languageCode: en-us
title: Foldable Robotics

theme: 
  - "hugo-cite"

enableInlineShortcodes: true

params: 
  menu:
    - name: Modules
      link: /modules
      external: false
    - name: Tutorials
      link: /tutorials
      external: false
    - name: Assignments
      link: /assignments
      external: false
    - name: Canvas Calendar
      link: https://canvas.asu.edu/calendar#view_name=month
      external: true
    - name: Canvas
      link: https://canvas.asu.edu/courses/71725
      external: true
  author: Daniel M. Aukes
  home: ""
    
    
taxonomies:
  type: types

ignorefiles:
  - "content/modules/biomechanics/_drafts"
  - "content/modules/introduction/_drafts"
  - "content/modules/integration/_drafts"
  - "content/modules/dynamics/_drafts"
  - "content/modules/compliance/_drafts"
  - "assignments/_drafts"  