baseURL: ""
languageCode: en-us
title: Site Name

theme: 
  - "hugo-cite"

enableInlineShortcodes: true

params: 
  author: Author Name
  home: ""
  description: Description

ignorefiles:
  - "content/modules/biomechanics/_drafts"
  - "content/modules/introduction/_drafts"
  - "content/modules/integration/_drafts"
  - "content/modules/dynamics/_drafts"
  - "content/modules/compliance/_drafts"
  - "assignments/_drafts"  